<?php
function dashboard_menu(){
    $items = array();

    $items['dashboard'] = array(
        'title' => 'Dashboard',	
        'page callback' => 'dashboard_content',
        'access callback' => 'user_access',
        // 'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );

    // Done by Subham 21/06/2024
    $items['profile'] = array(
      'title' => 'User Profile',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('user_profile_form'),
      'file' => 'include/user_profile.inc',
      'access arguments' => array('access content'),
    );

    return $items;
}

function dashboard_content() {
  // Done by Subham 20/06/2024 & 21/06/2024
  global $user, $user_role;
  // print_r($user_role);die;
  if($user_role == 4 || $user_role == 5){
    $output['user_info'] = getHRMSUserData($user->name); 
    $output['user_info']['email'] = isset($output['user_info']['email'])? $output['user_info']['email'] : (($user->mail!='') ? $user->mail : 'N/A');
  }else if($user_role == 6 || $user_role == 7 || $user_role == 8 || $user_role == 10 || $user_role == 11){

    $roleArr = $user->roles; 

    $output['user_info']['applicantName'] = $user->name;
    $output['user_info']['mobileNo'] = 'N/A';
    $output['user_info']['applicantDesignation'] = $roleArr[$user_role];
    $output['user_info']['email'] = $user->mail;
  }
  return theme('custom_dashboard_template', $output);
}

function dashboard_theme() {
    return array(
      'custom_dashboard_template' => array(
        'variables' => array(),
        'template' => 'custom-dashboard-template',
      ),
    );
}
